In [37]:
import pandas as pd
import numpy as np
data = pd.read_csv('categorical_test.csv', header=None)
data.head()

0  1  2  3  4  5  6  7  8  9
0  1  2  2  0  1  0  1  2  0  1
1  3  0  4  4  2  2  1  3  0  0
2  1  1  2  0  1  2  1  3  0  0
3  2  2  2  0  1  1  0  2  0  0
4  1  2  3  0  1  2  0  1  0  0

In [38]:
data = data.to_numpy()
print(data)
print(data.shape)

[[1 2 2 ... 2 0 1]
 [3 0 4 ... 3 0 0]
 [1 1 2 ... 3 0 0]
 ...
 [4 0 4 ... 2 0 0]
 [3 0 0 ... 1 0 0]
 [3 1 3 ... 2 0 1]]
(286, 10)


In [39]:
X = data[:,:-1]
print(X)
print(X.shape)
y = data[:,-1]
print(y)
print(y.shape)

[[1 2 2 ... 1 2 0]
 [3 0 4 ... 1 3 0]
 [1 1 2 ... 1 3 0]
 ...
 [4 0 4 ... 1 2 0]
 [3 0 0 ... 1 1 0]
 [3 1 3 ... 0 2 0]]
(286, 9)
[1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0
 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0
 0 1 1 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 1 1 0
 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0
 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1
 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1]
(286,)


In [40]:
print(np.unique(y))

[0 1]


In [42]:
print(np.where(y==1))

(array([  0,  10,  12,  15,  16,  17,  18,  21,  22,  26,  32,  37,  39,
        46,  64,  67,  70,  72,  75,  76,  78,  79,  84,  85,  89,  97,
        99, 100, 101, 102, 103, 106, 108, 109, 113, 115, 122, 130, 132,
       133, 134, 143, 145, 148, 150, 153, 154, 163, 176, 179, 180, 183,
       184, 185, 186, 191, 192, 193, 194, 199, 200, 204, 206, 209, 211,
       212, 215, 217, 220, 227, 230, 231, 235, 236, 237, 242, 243, 246,
       256, 265, 275, 278, 280, 282, 285]),)


In [43]:
print(X[np.where(y==1)])

[[ 1  2  2  0  1  0  1  2  0]
 [ 1  2  5  0  1  0  1  3  0]
 [ 4  0  6  5  2  2  0  2  0]
 [ 2  2  5  0  2  2  1  5  0]
 [ 4  0 10  0  1  2  1  3  0]
 [ 2  2  5  0  1  2  1  5  0]
 [ 1  2  3  0  1  2  0  3  1]
 [ 3  2  5  0  1  2  1  3  1]
 [ 4  0  5  0  2  1  1  5  1]
 [ 1  2  3  4  2  1  0  2  0]
 [ 1  2  5  0  1  1  0  3  0]
 [ 3  0  5  5  2  1  0  4  1]
 [ 5  0  2  6  0  0  0  2  1]
 [ 2  2  3  4  2  1  0  2  1]
 [ 3  0  6  0  1  1  0  2  0]
 [ 2  2  4  0  1  2  0  5  0]
 [ 3  2  4  0  1  0  1  3  0]
 [ 3  0  5  5  2  2  0  4  0]
 [ 3  2  4  0  1  1  0  5  0]
 [ 2  2  5  1  2  2  0  3  1]
 [ 2  2  7  0  1  0  0  2  0]
 [ 4  0  7  4  2  2  1  2  0]
 [ 2  2  5  2  2  2  0  2  0]
 [ 1  2  6  0  1  2  0  2  0]
 [ 2  2  4  0  1  1  1  2  0]
 [ 4  0  1  5  2  2  0  3  1]
 [ 4  0  3  0  1  0  1  3  0]
 [ 3  2  5  0  1  2  0  5  0]
 [ 1  2  4  4  2  2  0  2  1]
 [ 1  2  2  5  2  2  0  2  1]
 [ 2  2  2  0  1  1  0  3  0]
 [ 2  2  4  0  1  1  0  2  1]
 [ 2  0  3  0  1  1  1  3  0]
 [ 2  0  5

In [49]:
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()
X, y = iris['data'], iris['target']
N, D = X.shape
Ntrain = int(0.8 * N)
Xtrain = X[:Ntrain]
ytrain = y[:Ntrain]
Xtest = X[Ntrain:]
ytest = y[Ntrain:]
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [45]:
print(np.unique(y))

[0 1 2]


In [50]:
print(np.bincount(ytrain)/len(ytrain))

[0.41666667 0.41666667 0.16666667]


In [51]:
cou = []
for i in np.unique(ytrain):
    cou.append(np.sum(ytrain==i)/len(ytrain))
print(cou)

[0.4166666666666667, 0.4166666666666667, 0.16666666666666666]


In [52]:
print(Xtest)

[[6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
